module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./atoms/*.js",
    "./atoms/**/*.js",
    "./atoms/**/**/*.js",
    "./molecules/*.js",
    "./molecules/**/*.js",
    "./molecules/**/**/*.js",
    "./organisms/*.js",
    "./organisms/**/*.js",
    "./organisms/**/**/*.js",
    "./stories/*.js",
    "./stories/**/*.js",
    "./pages/**/*.{html,js}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{html,js}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
};
