import "styles/globals.css"
import Provider from "./provider";
import flagsmith from "flagsmith/isomorphic";
import Navbar from "@/molecules/Navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {

  const flagsmithState = await flagsmith
    .init({
      environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_KEY
    })
    .then(() => {
      return flagsmith.getState();
    });

  return (
    <html lang="en">
      <body>
        <Provider flagsmithState={flagsmithState}>
          <Navbar />

          {children}
        </Provider>
      </body>
    </html>
  )
}
